### ISSUE TITLE
Add a messageBubble type, add option to set open status on loading

### ISSUE THREAD

**Issue by justmy-solution** [JuzSer/vue-bot-ui#1]
Can we add a messageBubble type? like as google canlendar.
This is a chatbot example with calendar appointment.
https://truchat.io/rtgc/rtgc-4003/?utm_source=truchat-rtgc-gallery&gclid=CjwKCAjw3-bzBRBhEiwAgnnLCgZShmnNF9roJ29JbJcK02iNCulHU9jGXW2OcR5cEPAPEA7hz9g-vhoC5SUQAvD_BwE

You can complete all questions til last and check schedule calendar.

And I'd like to add an option for open-status on loading time.
Thanks.

**Comment by juzser** [comment]
Hi there, 

- About the first steps in your reference, you can do the same just by using the text & button message type. 

- About the calendar, I think that's not a common component and shouldn't be in this package. Because that seems like a custom type and used for your project only.

- I will add the `isOpen` prop soon.

**Comment by juzser** [comment]
Updated
