### ISSUE TITLE
Improve is-open prop

### ISSUE THREAD

**Issue by enorenio** [JuzSer/vue-bot-ui#8]
Make it object, introducing ability to make a delay (in ms) before showing board.
example:
```javascript
{
  delay: 2000,
},
```

**Comment by juzser** [comment]
Nice idea, 
Can you collaborate to update it and create a Pull Request? I will review, merge and bump to a new version. 
Unless it may take me about 2 weeks, because I'm overloading with a ton of works now. 

Btw, I think we should have another prop like `open-delay` rather than change the `is-open` into object, it's more efficient and easier to understand.

**Comment by enorenio** [comment]
@juzser Sure, I will do it soon. Nice point about `open-delay`, I'll do it that way.

**Comment by enorenio** [comment]
@juzser I finished working on it and now I wanted to push, but have no permission to push the branch. Can you please allow me? Then I will create Pull Request.

**Comment by juzser** [comment]
Wow, thank you @enorenio!
You can fork this repo > push the new code to your `master` branch > Create a Pull Request on this repo to merge this repo's `master` branch to your `master`, so I can check & review the PR.

**Comment by enorenio** [comment]
I hope I did everything right. Now I'm waiting for your review. I'm excited to contribute to your repo @juzser

**Comment by juzser** [comment]
Thank you @enorenio !
I merged your PR and release a new minor version. 

Hopefully we can collaborate more in the future. 
I will be back and update this repo as soon as I'm available. 

Close this ticket due to PR has been merged.
